### ISSUE TITLE
Unassociated database usage

### ISSUE THREAD

**Issue by leatherking** [defog-ai/defog-python#11]
Hi,
How can I use the API without accosiating my database? Just like the sqlcoder-demo, I wanna post my requests with question and table schema.

**Comment by wongjingping** [comment]
Hi @leatherking could you clarify what do you not want to share specifically? We do not use any data from your database, only the metadata of the tables/columns in it.

**Comment by leatherking** [comment]
Thanks. @wongjingping 
Not the security concern, but I am researching on Text2SQL. I would like to evaluate the preformance of sqlcoder on spider dev

**Comment by wongjingping** [comment]
Got it. You should be able to use the code [here](https://github.com/defog-ai/sqlcoder/blob/9bba22a346aca67ab1f1398cf61c687facbdafd6/inference.py) to test sqlcoder. Closing this as the question is for another repo.
