### ISSUE TITLE
Unable to generate query successfully

### ISSUE THREAD

**Issue by wkshens** [defog-ai/defog-python#13]
Hi, I am using your Python library to convert a query to SQL and run it on a PostgreSQL DB. However, when I run the script, it tells me that it has failed to run and that there is no error message at all. Why is this occurring? 

My DB has only 1 table, 130K rows, and 14 columns. I am also using a free defog account.

Thank you!

![image](https://github.com/defog-ai/defog-python/assets/149129671/52905b34-baa2-4dc9-a206-6b9a38b141c3)
![image](https://github.com/defog-ai/defog-python/assets/149129671/f59d78e2-cc55-4ed6-962b-6c9af1aa96f1)

**Comment by wongjingping** [comment]
Hi @wkshens , thanks for raising this issue. Unfortunately we can't debug further without more details from you. Could you drop us an email at support@defog.ai with the email you registered with and the api_key if you have it?

**Comment by wkshens** [comment]
Hi @wongjingping , I have sent you an email containing the api_key. Thanks!

**Comment by wongjingping** [comment]
We got - we'll follow up over there, thank you!

**Comment by Jayuda** [comment]
i got same error on mysql. how to solved this  ?
